image: ubuntu:18.04

before_script:
  - apt update
  - apt install python python3 wget sudo -y

stages:
  - Build

Build LibreWolf:
    stage: Build
    script:
        - cd browser
        - ./build.sh
    artifacts:
        paths:
            - "browser/librewolf*.tar.bz2"
