image: ubuntu:18.04

stages:
  - Build
  - Release

Build LibreWolf:
    stage: Build
    script:
        - cd browser
        - ./build.sh
    artifacts:
        paths:
            - "browser/build_output"

Release to Gitlab:
  stage: Release
  image: python3
  script:
    - pip3 install gitlab-release
    - gitlab-release browser/build_output/*
  only:
    - tags
