image: ubuntu:18.04

stages:
  - Linux-Build
  - Release

Build Linux Packages:
    stage: Linux-Build
    script:
        - cd browser/linux
        - ./build.sh
    artifacts:
        paths:
            - "browser/linux/LibreWolf.tar.bz2"

Release to Gitlab:
  stage: Release
  image: python3
  script:
    - pip3 install gitlab-release
    - gitlab-release browser/linux/build_output/*
  only:
    - tags
