image: ubuntu:18.04

stages:
  - Linux-Build
  - Release

Build Linux Packages:
    stage: Linux-Build
    script:
        - cd browser/linux
        - echo 0 > /proc/sys/kernel/userns_restrict
        - bwrap --dev-bind / / bash
        - ./build.sh
    artifacts:
        name: "Librewolf-$CI_COMMIT_REF_NAME-Linux-Packages"
        paths:
            - "LibreWolf.tar.bz2"
            - "LibreWolf.AppImage"
            - "librewolf-flatpak-repo"
            - "LibreWolf.flatpak"

Release to Gitlab:
  stage: Release
  image: python3
  script:
    - pip3 install gitlab-release
    - gitlab-release LibreWolf.tar.bz2 LibreWolf.AppImage librewolf-flatpak-repo LibreWolf.flatpak
  only:
    - tags
